# Site settings
title: Theodore Nordsieck
email: 
description: > # this means to ignore newlines until "baseurl:"
  Mostly programming, economics and history.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://nordsieck.github.io" # the base hostname & protocol for your site
twitter_username: nordsieck
github_username:  nordsieck

# Build settings
markdown: kramdown
